### PR TITLE
feature/3d-editor-control-BUS-6

### PR DESCRIPTION
**Pull request by pscheede**

### CODE REVIEW

**Review by stefan-rink — DISMISSED** [review]
Nice!

**Review by luismoser99 — DISMISSED** [review]
Great!

**Review by stefan-rink — DISMISSED** [review]

**Review by luismoser99 — DISMISSED** [review]
Perfect!

**Review by stefan-rink — APPROVED** [review]

**Review by luismoser99 — APPROVED** [review]
OK!

**Pull request merged**
